accounts:
  _worked: &worked
    - user1: pass1
    - user2: pass2
    - user3: pass3
    - user4: pass4
    - user5: pass5

  _non-worked: &non_worked
    - user3: pass3 
    - user4: pass4 

templates:
  template1: &template1
    - { name: "services/*/environment/login_mindoo_mileage", to: *worked, method: roulette, part: key }
    - { name: "services/*/environment/password_mindoo_mileage", to: *worked, method: roulette, part: val }

default: *template1
